### ISSUE TITLE
麻烦问下密码？

### ISSUE THREAD

**Issue by MuziShaoxing** [LukeShortCloud/winesapOS#167]
引导第一屏幕的密码两个都不对呀
没有地方可以切换用户

**Comment by LukeShortCloud** [comment]
Were you able to log in?

The password should be the same as the username. For Mac Linux Gaming Stick (major version 1 and 2) that is "stick". For winesapOS (major version 3) that is "winesap"

For the secure image, it is confusing as the LightDM software requires you to log in, confirm your password, then type in the new password twice. There is not much we can do about that from the software side. What I can do is add more documentation around the passwords.

**Comment by MuziShaoxing** [comment]
I can log in. I found the password in the old document. Maybe there was a short circuit in my brain at that time, so I didn't expect that the password and account number were the same
The experience of the old version is still good, but there is no Chinese
Your new development version, I don't know why all the applications can't be opened after entering the system for a few minutes. It feels like the USB chain is broken


Note: I don't know much English. Please forgive me for the online translation of input method


 
---原始邮件---
发件人: "Luke ***@***.***&gt;
发送时间: 2022年2月6日 02:07:03
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [LukeShortCloud/winesapOS] 我运气真好，第一次玩这个你就改了密码 (Issue #167)




 
Were you able to log in?
 
The password should be the same as the username. For Mac Linux Gaming Stick (major version 1 and 2) that is "stick". For winesapOS (major version 3) that is "winesap"
 
For the secure image, it is confusing as the LightDM software requires you to log in, confirm your password, then type in the new password twice. There is not much we can do about that from the software side. What I can do is add more documentation around the passwords.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LukeShortCloud** [comment]
Your English online translation is good. Thank you for all of the feedback!

I am glad to hear you figured out the passwords. It can be confusing. I will add more documentation regarding that.

Short-term, I will add the ability to build images with Chinese (and other languages). Long-term, I want to add a first-time setup that can include changing the language.

The 3.0.0-alpha.0 release does have a bug in KDE Plasma where applications sometimes do not launch after the first boot. The short-term fix is to reboot. The long-term fix is to upgrade with the command `yay -Syyu`. I have been doing a lot of new development builds recently and I can confirm that the bug has been fixed.

We are always looking for ways to make the project better. The goal is to release 3.0.0 stable (based on Steam OS 3) in one or two months. If you want to help out with testing, I can create another alpha release build. We currently use Arch Linux instead of Manjaro while we are waiting for Steam OS 3. Let me know if there is anything else you would like to see implemented! :-)

**Comment by LukeShortCloud** [comment]
@MuziShaoxing We have our first beta now based on SteamOS 3 that you may be interested in trying!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.0.0-beta.0

**Comment by MuziShaoxing** [comment]
I have received your push. Recently, I am moving, broadband has not been migrated, but my network recovery support will definitely participate in the test for the first time.&nbsp;
I'm looking forward to your new product.&nbsp;
The above has Baidu input method for translation, if you have any questions, please try general understanding.&nbsp;
 
---原始邮件---
发件人: "Luke ***@***.***&gt;
发送时间: 2022年3月11日 10:20:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LukeShortCloud/winesapOS] 我运气真好，第一次玩这个你就改了密码 (Issue #167)




 
@MuziShaoxing We have our first beta now based on SteamOS 3 that you may be interested in trying!
 
https://github.com/LukeShortCloud/winesapOS/releases/tag/3.0.0-beta.0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
