### ISSUE TITLE
Gamescope does not support proprietary NVIDIA drivers

### ISSUE THREAD

**Issue by KaiH-0** [LukeShortCloud/winesapOS#237]
Is it possible to use something else other than gamescope so I can use this with a Nvidia graphics card. :)

**Comment by LukeShortCloud** [comment]
Hey @KaiH-0 , thanks for your comment!

I was not even aware that Gamescope did not work with the proprietary NVIDIA drivers. Thanks for the heads-up! Looks like we'll need to keep a close eye on this GitHub issue:

https://github.com/Plagman/gamescope/issues/151

That's a bummer. I'm not aware of any alternatives. Will post here if I find any.

We do not officially support NVIDIA right now. It's complicated because it's against their terms and the Linux license to distribute it. I'm working on a solution for the 3.1 release. I also have an NVIDIA gaming computer so I'm very interested in getting this working! Here's the related GitHub issue for that:

https://github.com/LukeShortCloud/winesapOS/issues/112

**Comment by LukeShortCloud** [comment]
winesapOS will still work out-of-the-box. Gamescope currently needs to be manually enabled on a per-game basis. We're working on implementing a system-wide variant of this to align closer with SteamOS 3. Most likely something for the 3.1 or a later release.

**Comment by LukeShortCloud** [comment]
@KaiH-0 Here's our new GitHub issue tracking global Gamescope support. I'll make sure to handle the NVIDIA use-case (disabling it for now).

https://github.com/LukeShortCloud/winesapOS/issues/240

**Comment by LukeShortCloud** [comment]
Good news, NVIDIA is actively working on supporting Gamescope!

https://www.phoronix.com/scan.php?page=news_item&px=Gamescope-NVIDIA-Pending

**Comment by LukeShortCloud** [comment]
I last tested Gamescope on my NVIDIA graphics card two weeks ago using the stable driver. It didn't work. We probably need both (1) an updated NVIDIA driver and (2) an updated Gamescope package. We also want to only ship stable drivers and packages. It's still definitely worth testing and continuing to figure it out before it's all marked as stable.

SteamOS is very slow at providing operating system updates. Specifically for upstream Arch Linux packages such as NVIDIA drivers. They have not been updated since January (4 months now). There are a few solutions around that that we are exploring.

**Comment by LukeShortCloud** [comment]
We need to set `nvidia-drm.modeset=1` as a kernel argument for NVIDIA. It also seems that there are still lots of issues with NVIDIA support in gamescope. Refer to: https://github.com/Plagman/gamescope/issues/497

**Comment by LukeShortCloud** [comment]
For NVIDIA laptops, it's required to use `gamescope -- prime-run ${PROGRAM}` to run programs with gamescope.

**Comment by LukeShortCloud** [comment]
For NVIDIA laptops and using the Flatpak, it's required to use `gamescope --prefer-vk-device <PCI_ID_VENDOR>:<PCI_ID_MODEL> -- prime-run ${PROGRAM}`.

`https://github.com/ValveSoftware/gamescope/issues/848`

**Comment by LukeShortCloud** [comment]
Since gamescope uses Wayland and Vulkan, I believe the NVIDIA 545 driver should fix any lingering issues: https://www.phoronix.com/news/NVIDIA-545-Wayland-VLK-PRIME

**Comment by LukeShortCloud** [comment]
Unfortunately, NVIDIA still provides poor support for Gamescope. This appears to be a driver limitation in the proprietary and open kernel module driver. I've been thinking about closing this out for a while because (1) there is literally nothing I can do about this and (2) the new open source NVK driver in Mesa should work. Even the community-maintained gamescope-session project recently started removing NVIDIA support:

https://github.com/ChimeraOS/gamescope-session/commit/bfde77d4330721ee757ec21c52cac44c5953df73

Here is a list of just a few known issues with Gamescope and NVIDIA:

- https://github.com/ValveSoftware/gamescope/issues?q=is%3Aissue+is%3Aopen+nvidia
    - `https://github.com/ValveSoftware/gamescope/issues/896`
    - `https://github.com/ValveSoftware/gamescope/issues/835`
    - `https://github.com/ValveSoftware/gamescope/issues/708`
    - `https://github.com/ValveSoftware/gamescope/issues/689`
    - `https://github.com/ValveSoftware/gamescope/issues/599`
    - `https://github.com/ValveSoftware/gamescope/issues/555`

I'm closing this request to support the proprietary NVIDIA driver with Gamescope. As an alternative, users will need to wait for the open source NVK driver to mature. It needs additional Linux kernel development and the ability to use the GSP firmware to run the graphics cards at higher clock speeds. I suspect this will happen by the end of this year. winesapOS will include these changes when they are available.

For AMD and Intel GPUs, we will be enabling gamescope-session for them globally in the near future.
