### ISSUE TITLE
SteamOS Game Mode session

### ISSUE THREAD

**Issue by KaiH-0** [LukeShortCloud/winesapOS#241]
Do you have a separate steamos session? So it goes straight to steam on startup? As making it automatically startup in the desktop environment would make some games start windowed.

**Comment by LukeShortCloud** [comment]
@KaiH-0 We boot into the KDE Plasma desktop by default. Are you asking for a separate session dedicated to Steam similar to how the Steam Deck does it? We do not have that implemented right now.

By the way, do you have a Steam Deck? Mine is not expected to arrive until next month (best-case scenario).

**Comment by KaiH-0** [comment]
No I don't sorry but I love the UI, I saw your announcement about next week a major release, do you think a dedicated steam session would be included in that? :)

**Comment by LukeShortCloud** [comment]
There are some guides I've seen online for how to force the new Steam Deck UI in any Steam client. I won't be pursuing that because Valve said they will be rolling that our to all Steam users eventually as a replacement for the Big Picture Mode.

Making a whole separate session is a hard task but would benefit by adding global AMD FSR and Gamescope support. From other guides I've seen, the KDE Plasma desktop is not even running (thus saving resources) when the Steam Deck boots. That will require more reverse-engineering and research. I'll see if we can add it to a future release. It'll be a lot easier to figure this stuff out once I receive my Steam Deck.

For now, we do have a huge beta release coming out this week! You'll then be able to get hands-on with SteamOS via winesapOS and help provide more feedback. All you need is a spare external drive.

Thanks for all of your suggestions so far! Keep them coming. :-)

**Comment by LukeShortCloud** [comment]
I renamed the title of this feature request to reflect that it's officially called Game Mode (not to be confused with the "gamemode" program). This is still a work-in-progress.

**Comment by LukeShortCloud** [comment]
Here is how people have implemented the equivalent Game Mode from SteamOS 1 and 2:

```
https://askubuntu.com/questions/302488/can-i-run-steam-as-its-own-standalone-session
```

I wonder if anything has changed with this setup in SteamOS 3.

**Comment by LukeShortCloud** [comment]
ChimeraOS created the `gamescope-session` project to have a similar experience to what SteamOS 3 has. It is cross-platform and hosted on the AUR.

https://github.com/ChimeraOS/gamescope-session

**Comment by LukeShortCloud** [comment]
This is how SteamOS handles it. It is very Steam Deck specific: https://github.com/theVakhovskeIsTaken/gamescope-steamos-pkgbuild/blob/master/gamescope-session

**Comment by LukeShortCloud** [comment]
It is worth noting that `gamescope-session` is still experimental for all non-AMD devices:

- Intel = Reported as of 30 minutes ago, Intel support is still experimental. https://github.com/ChimeraOS/gamescope-session/blob/9a2d5ebb328dc9cb15484203774b7dff7045a9f7/usr/share/gamescope-session/device-quirks#L15
- NVIDIA = NVIDIA support is still a work-in-progress. https://github.com/LukeShortCloud/winesapOS/issues/237

**Comment by LukeShortCloud** [comment]
@KaiH-0 winesapOS 3.4.0 is out now with a Game Mode for Steam and Open Gamepad UI! This works best on AMD, mostly on Intel, and not at all on NVIDIA yet (still waiting on NVK).

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
