### ISSUE TITLE
Intel iGPU driver doesn't load on the LTS kernel on the 3.0 beta

### ISSUE THREAD

**Issue by ThePenguinUser** [LukeShortCloud/winesapOS#261]
Hi. I have an Intel HD 630 iGPU in my laptop and I booted off the linux-lts kernel and plasma reports the iGPU as llvmpipe and hardware acceleation is not working. The linux-naptune kernel doesn't boot at it shows a black screen with mouse pointer after the plasma splash screen.

**Comment by LukeShortCloud** [comment]
Thanks for the bug report!

This is why we have more than one Linux kernel installed, in case one does not work. I wonder if the Neptune kernel from SteamOS requires newer hardware support. Not much we can do as that is all in Valve's hands. I'm glad that at least the Linux LTS kernel gets you further.

I dusted off some old laptops I had lying around to help with testing. My Intel HD Graphics 5500 works fine using the Intel OpenGL and Vulkan drivers from Mesa. That's strange because my iGPU and yours came out in the same year (2015). My Intel HD Graphics 3000 (from 2011) did not work and, similar to you, it reverted back to CPU-based rendering.

----

**Could you provide the full output of these two commands?** You can copy and share the text via a https://pastebin.com/ link.

```
glxinfo
vulkaninfo
```

**Could you also test with our 3.0.0-alpha.1 release and see how that compares?** That one is based on Arch Linux so it uses a different and more stable graphics drivers compared to SteamOS. Believe it or not, SteamOS ships with newer and unreleased Mesa drivers built directly from git to their Steam Deck devices. We're shipping those same drivers in our 3.0.0-beta.0 release.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.0.0-alpha.1

**Comment by ThePenguinUser** [comment]
Here is the full output of the glxinfo command:
https://pastebin.com/inR32JeK

And vulkaninfo:
https://pastebin.com/EgNB4ryT

Later I will bring up another external HDD to try the 3.0.0-alpha.1 release

**Comment by ThePenguinUser** [comment]
On 3.0.0-alpha.1 the driver loads just fine

**Comment by LukeShortCloud** [comment]
Thanks for providing that information. I can see that OpenGL is using llvmpipe (the CPU driver) and Vulkan is using the Intel driver (the GPU driver).

SteamOS 3 is not open source yet so we can't look at the source code or how the packages are built. That means troubleshooting this will be hard to impossible. I'll see if I can spot any obvious differences between the Arch Linux and SteamOS packages such as missing files.

There is good news. I see a few possible solutions for you.

**(1) Use Zink.** Since your Vulkan driver is using the correct Intel driver, you can use this OpenGL-to-Vulkan translation layer. Here's how you can enable it:

```
echo MESA_LOADER_DRIVER_OVERRIDE=zink | sudo tee -a /etc/environment
export MESA_LOADER_DRIVER_OVERRIDE=zink
```

Then verify it's using Zink:

```
glxinfo | grep renderer
```

I did some research for how Mesa handles OpenGL drivers. It's difficult to impossible to manually switch it to a specific back-end. It just automatically detects the right one to use.

**(2) Uninstall AMD drivers.** This is a problem I encountered once very long ago. By having both AMD and Intel drivers installed (which winesapOS does have both), the system may get confused on which one to load. I'll see if I can come up with a full list of packages that should be removed.

**(3) Use Arch Linux.** Although not as interesting as running SteamOS, you still get all the benefits of a gaming optimized and portable Linux experience. We support building winesapOS from scratch with Arch Linux, Manjaro, or SteamOS. We restrict our build to virtual machines today but I can modify our documentation and installer to handle baremetal. This is something I've been meaning to do anyways but I can make it a higher priority if you're interested in building it yourself. Our release images that we provide will only target SteamOS from now on but users will always have the option to do their own build against Arch Linux or Manjaro instead.

https://github.com/LukeShortCloud/winesapOS/blob/main/DEVELOPER.md

**Comment by LukeShortCloud** [comment]
After re-reading my last comment, I realized that the Zink documentation literally is providing an environment variable to change the OpenGL Mesa driver back-end. A quick search lead me to a 4th possible solution.

**(4) Use the old Intel driver.**

```
echo MESA_LOADER_DRIVER_OVERRIDE=i965 | sudo tee -a /etc/environment
export MESA_LOADER_DRIVER_OVERRIDE=i965
```

Then verify it's using that driver:

```
glxinfo | grep renderer
```

https://wiki.archlinux.org/title/intel_graphics#Old_OpenGL_Driver_(i965)

**Comment by LukeShortCloud** [comment]
Okay, I found the real problem here: SteamOS does not ship OpenGL drivers for Intel. Only AMD and the software renderer. They do, however, provide Vulkan drivers for both AMD and Intel.

Moving forward, our best option is to enable Zink by default.

**Comment by LukeShortCloud** [comment]
Here are my test results with using Zink:

- AMD Radeon Pro 5300M = Corrupted graphics (only linux-lts [5.15] boots).
- Intel HD Graphics 5500 = Black screen with cursor (all kernels).
- Intel HD Graphics 3000 = Black screen no cursor (all kernels). This card only has a partial community implementation of Vulkan 1.1.

So far, this shows that the software/CPU renderer for OpenGL is more reliable for desktop usage but there would be a huge performance hit for gaming. Thinking aloud about how winesapOS can further handle this: (1) start game launchers with Zink enabled or (2) ship an Arch Linux 3.0.0 stable release of alongside our SteamOS one. We, unfortunately, have no control over the SteamOS software stack at this point in time.

@ThePenguinUser What happens when you use Zink with the 3.0.0-beta.0 release? For ensuring it loads up properly, add this entry to your environment file then reboot your machine. Fair warning: you may be unable to get to a usable desktop if this does not work on your machine.

```
echo MESA_LOADER_DRIVER_OVERRIDE=zink | sudo tee -a /etc/environment
```

**Comment by LukeShortCloud** [comment]
@QushyQushy Could you also help test out Zink? See the comment above.

I'm curious how well it would work on a modern AMD dGPU since, according to your YouTube videos, you've got a 6800XT. It's possible you won't be able to access the desktop if it doesn't work, though.

**Comment by QushyQushy** [comment]
> MESA_LOADER_DRIVER_OVERRIDE=zink

Can't I just launch a KDE sesssion on a different TTY with `MESA_LOADER_DRIVER_OVERRIDE=zink XDG_SESSION_TYPE=x11 dbus-run-session startplasma-x11`? Otherwise I'll just make a new Winesap USB to test.

**Comment by QushyQushy** [comment]
> @QushyQushy Could you also help test out Zink? See the comment above.
> 
> I'm curious how well it would work on a modern AMD dGPU since, according to your YouTube videos, you've got a 6800XT. It's possible you won't be able to access the desktop if it doesn't work, though.

I just winged and set it in `etc/environment` and the graphics were all corrupted so I reverted back.

**Comment by LukeShortCloud** [comment]
In theory, yeah, starting another Plasma session in a different TTY should also work. I didn't think of that.

Thanks for confirming, I really appreciate it. This basically tells me that Zink is missing some capabilities for KDE Plasma to work. The main developer is likely only targeting video games right now.

This leaves us in a tough spot because SteamOS does not ship Intel OpenGL drivers and we cannot use Zink. I'll test out a few other solutions on my end.

**Comment by LukeShortCloud** [comment]
I tested enabling Zink for only game launchers. For example, here's how I tested Steam:

```
$ grep env ~/Desktop/steam_runtime_zink.desktop
Exec=env MESA_LOADER_DRIVER_OVERRIDE=zink /usr/bin/gamemoderun /usr/bin/steam-runtime %
```

Here are my test results:

- Heroic Games Launcher = Works.
- Lutris = Does not launch.
- Steam (Runtime) = Works.

Even with the Steam client working, I launched an OpenGL game (Lux Delux) and it had some rendering issues. Conclusion: Zink is not a viable production driver right now.

**Comment by LukeShortCloud** [comment]
Since supporting Intel is going to be a pain, we might as well support NVIDIA with the stable 3.0.0 release. Here's what I'm thinking in psuedo code:

```
if amd:
    pass
elif intel:
    if steamos:
        set environment variables for Arch Linux Mesa installed somewhere else
    else:
        pass
elif nvidia:
    pacman install nvidia drivers
```

Regarding Intel, we can use `pacman` to install the Mesa packages into a specified directory (instead of the default of the root `/` file system). This guide provides some nice hints on how to then use that directory.

```
MESA=$HOME/mesa \
LD_LIBRARY_PATH=$MESA/lib64:$MESA/lib:$LD_LIBRARY_PATH \
LIBGL_DRIVERS_PATH=$MESA/lib64/dri:$MESA/lib/dri \
VK_ICD_FILENAMES=$MESA/share/vulkan/icd.d/radeon_icd.x86_64.json:$MESA/share/vulkan/icd.d/radeon_icd.x86.json
```

https://gist.github.com/Venemo/a9483106565df3a83fc67a411191edbd#running-through-a-script-recommended-for-testing-a-single-game-or-app

**Comment by LukeShortCloud** [comment]
We can create a GUI for a simple shell script by using [zenity](https://medium.com/swlh/how-to-modernize-your-bash-scripts-by-adding-gui-cba613a34cb7).

**Comment by ThePenguinUser** [comment]
> Here are my test results with using Zink:
> 
> * AMD Radeon Pro 5300M = Corrupted graphics (only linux-lts [5.15] boots).
> * AMD Radeon HD 8280 = Black screen with no cursor (all kernels).
> * Intel HD Graphics 5500 = Black screen with cursor (all kernels).
> * Intel HD Graphics 3000 = Black screen with no cursor (all kernels). This card only has a partial community implementation of Vulkan 1.1.
> 
> So far, this shows that the software/CPU renderer for OpenGL is more reliable for desktop usage but there would be a huge performance hit for gaming. Thinking aloud about how winesapOS can further handle this: (1) start game launchers with Zink enabled, (2) install Mesa from Arch Linux into a chroot and configure Mesa to use that library path via an environment variable, or (3) ship an Arch Linux 3.0.0 stable release of alongside our SteamOS one. We, unfortunately, have no control over the SteamOS software stack at this point in time.
> 
> @ThePenguinUser What happens when you use Zink with the 3.0.0-beta.0 release? For ensuring it loads up properly, add this entry to your environment file then reboot your machine. Fair warning: you may be unable to get to a usable desktop if this does not work on your machine.
> 
> ```
> echo MESA_LOADER_DRIVER_OVERRIDE=zink | sudo tee -a /etc/environment
> ```

So I tested zink and on all kernels I get the black screen with cursor

**Comment by LukeShortCloud** [comment]
Thanks for confirming! That's unfortunate. Zink is not viable on AMD or Intel graphics. This is good to know.

**Comment by LukeShortCloud** [comment]
I opened an upstream issue for the Mesa project to see if they can help us get Zink working with the KDE Plasma desktop environment: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6150
