### ISSUE TITLE
Use SteamOS (Holo and Jupiter) repositories with upstream Arch Linux or Manjaro repositories

### ISSUE THREAD

**Issue by Daasin** [LukeShortCloud/winesapOS#281]
_**Sort of**_ like a Steamjaro, Holosap, or even a Wine(_sap_)jaro? With the only AUR Repos used being the ones that are in SteamOS 3's Image and the rest is Manjaro. 
 
That could have benefits of SteamOS while providing users access to Manjaro's Apps, but also Updates for those additional apps that are added by the users.

**Comment by LukeShortCloud** [comment]
In theory, this may be possible!

The tricky part is that SteamOS ships its own Arch Linux os, extra, community, and multilib repositories so that would conflict with other official mirrors (from Arch Linux or Manjaro, for example). I think if the Manjaro mirror is listed first in the Pacman mirror list and then the SteamOS mirror is listed second then this may work.

Related to this, we already have built-in support for building release images based on Arch Linux, Manjaro, or SteamOS. Our public release images will continue to be based on SteamOS only but we'd be happy to add in build support for you to do interesting things like this yourself. 🙂 Here's our developer documentation if you want to play around with winesapOS builds:

https://github.com/LukeShortCloud/winesapOS/blob/main/DEVELOPER.md

**Comment by LukeShortCloud** [comment]
Also related, I have a feeling that the Linux kernel (Neptune), KDE Plasma theme (Vapor), and even the Mesa graphics library from SteamOS 3 will end up in the AUR. Heck, I've been considering taking ownership of one or all of those myself. That'd be my preferred way of handling this hybrid. The SteamOS repositories (Holo and Jupiter) have a handful of conflicting packages with Arch Linux that already make it painful for us to support today.

https://github.com/LukeShortCloud/winesapOS/issues/234

**Comment by LukeShortCloud** [comment]
@Daasin Good news, we fully support a hybrid Arch Linux + SteamOS installation! In fact, starting with 3.1.0, we plan to default to that. A bit more work is needed for us to also support a Manjaro + SteamOS installation but it shouldn't be too hard.

**Comment by LukeShortCloud** [comment]
@Daasin The Manjaro + SteamOS hybrid is now supported! It requires loading up the Manjaro ISO / live media, downloading the winesapOS installer files, and then setting this environment variable before starting the install:

```
export WINESAPOS_DISTRO=steamos
```

We'll add more proper documentation around this process.
