### ISSUE TITLE
Clean build AUR pkgbuilds and provide a repository

### ISSUE THREAD

**Issue by FabioLolix** [LukeShortCloud/winesapOS#291]
Clean build AUR pkgbuilds using `devtools` (extra-x86_64-build) and provide a repository with them (btw Google Chrome have an unredestributable license)

**Comment by LukeShortCloud** [comment]
I'm not sure what you mean. Could you explain more?

When we install packages from the AUR right now we basically run `yay -S --noconfirm`. The base image provides all clean builds and we even wipe the `~/.cache/yay/` directory as one of our last build steps. winesapOS itself does not provide any of our own packages outside of Arch Linux, SteamOS, or AUR repositories.

Thanks for the heads-up about Google Chrome! We've been trying really hard to avoid installing unredestributable software. We can easily make that part of our first-time setup instead.

**Comment by FabioLolix** [comment]
Building packages in a clean chroot like Arch packagers do, this ensure that needed depends and makedepends are met and that there isn't unwanted dynamic linking

https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

For making an Arch repository a static web server is enough, hosting on SourceForge is too slow (for the countdown at download), it could be also done commiting the packages to a git repo on Github or Gitlab; not the most elegant solutions but work and is free (at least on github there was a file size limit in upload of ~200MB years ago)

Also configure packager field in makepkg.conf

**Comment by LukeShortCloud** [comment]
Thank you so much for all of the advice! I've only ever made a couple of PKGBUILDs before and did not know about the devtools package and building in a chroot. That seems really useful to isolate dependencies. Setting the packager is also important so I'll be sure to do that.

I've been thinking a lot about this and you're probably right that winesapOS will need its own package repository. A lot of AUR packages we install today will likely switch over to Flatpaks. For everything else (ex., system packages), we should ideally have our own repository with packages pre-built. Otherwise, updates will take up a lot of time and space compiling everything. From SteamOS 3, I at least want to rebuild their custom Mesa package to re-enable Intel driver support for OpenGL.

Free is always good! I'm very frugal so I like to save money. I do have my own web server I can use for hosting the packages so I'll explore a few different options between that, SourceForge, and GitHub/GitLab. The first question I need to figure out is how much traffic and bandwidth do I expect to get from my own winesapOS package repository.

Thanks for lending your knowledge and experience! I'm glad to be learning from *the* PKGBUILD expert who maintains over 200+ AUR packages. Kudos to you on that! :-)

**Comment by LukeShortCloud** [comment]
I am planning on hosting built packages at: https://winesapos.lukeshort.cloud/repo/

**Comment by FabioLolix** [comment]
For continuing discussion about pkgbuilds

From https://github.com/LukeShortCloud/winesapOS/issues/312#issuecomment-1084064825

> I've been reading over the [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines) page. Is there an approval process for AUR packages? Or is it available as soon as I push something to the AUR package repository? Should I also make a separate git repository on GitHub for each PKGBUILD? I'd like to publish a linux-steamos and mesa-steamos package. I'm hoping to follow AUR best practices. :-)

There is no approval process (unfortunately), pkgbuilds are available as soon as you push, but I guess you already know by now

A git repository with all pkgbuilds is more convenient imho

You can import all AUR git repos singularly here on github so a pull request approved here can be send directly to AUR but when you have dozens of pkgbuilds don't seem convenient, also you might need or want corrected or changed AUR pkgbuilds at your hand.

About `linux-steamos` pkgbuild

* Don't ovverride the number of makejobs (-j $(nproc)) instead configure your `/etc/makepkg.conf`, you can copy it in your home with dot prefix if you don't want to modify the one in /etc

About `mesa-steamos` and `lib32-mesa-steamos` pkgbuilds

*  replaces=('mesa-libgl') is not needed, provides and conflicts are sufficient, the Arch pkgbuild have it but for AUR pkgbuilds it can be counterproductive, the change have been introduced I don't know how many months or years ago and users need to update their system before complaining about stuff

* FYI using git tag in source=() and then using pkgver() is unusual (I wouldn't say incorrect, only unusual), usually is used a commit and pkgver() extract the tag

* `lib32-mesa-steamos` very likely need to depends on `mesa-steamos` (as lib32-mesa-git depends on mesa-git). AUR helpers are usually unsuitable for this task as they tend first to uninstall mesa and then there is the problem with dependencies, as seen here https://forum.manjaro.org/t/how-to-install-mesa-git/100982 (with a proposed solution)

About pamac-all and libpamac-all

* need `snapd` which according to Garuda packagers is an hassle to deal with, they packaged it but no longer do
* About #318 one solution can be to use an older Vala version, Vala have different branches; see https://wiki.gnome.org/Projects/Vala, some but not all are on the AUR and can be easily added or modified from my experience
* Errors done by AUR maintainer with [this fix](https://aur.archlinux.org/cgit/aur.git/commit/?h=libpamac-full&id=defcf36bafb43c30ac110733507665edca39ae4b) for libpamac-full
  + using git sources without adding git as makedepends
  + not specifying a commit to build, it is effectively a VCS pkgbuild now
  + no pkgver added, there is no longer correlation between pkgver= and source=()

**Comment by LukeShortCloud** [comment]
Thanks for all of the great feedback!

- AUR packaging = I'll stick with just the AUR git repository for now as, you're right, it seems like it'd be largely inconvenient to have two git repositories.
- \*-steamos PKGBUILDs = Thanks for the individual suggestions for each of those packages. Most of the PKGBUILDs are a copy and paste from what Valve was originally using. I'll be sure to go back and make the proper modifications. I also was not aware of the `makepkg.conf` configuration so I'll use that for changing the `make` parameters during a `makepkg` run.
- pamac = I appreciate the hints. I'm running another build of winesapOS now to see if the latest libpamac-full changes help. Otherwise, I'll just setup my repository with the old version of Vala and make sure it's installed before pamac-all.

**Comment by LukeShortCloud** [comment]
I've addressed the major issues with the AUR packages and have our repository online. Other issues are open to track the addition of more documentation about the repository itself. Regarding the packages, the versioning I'll leave the same to align with what SteamOS uses. That'll make rebasing easier. Closing as resolved. Thanks again for your help, FabioLolix!
