### ISSUE TITLE
Not booting when choosing in GRUB

### ISSUE THREAD

**Issue by chenxi050402** [LukeShortCloud/winesapOS#327]
In the grub interface, if anything is chosen, it will freeze until you press a key then the screen goes black and shows the text "Windows Boot Manager", and it shows "Enter Setup" when you press down twice

**Comment by chenxi050402** [comment]
The system is a GPD Win Max with an i5 1035g7

**Comment by LukeShortCloud** [comment]
I believe this is related to this issue: https://github.com/LukeShortCloud/winesapOS/issues/324 . The summary is that SteamOS provides little support for NVIDIA GPUs and no support for Intel out-of-the-box. Our workaround in 3.0 was to hope that the software/CPU rendering of graphics was good enough to get you to our first-time setup wizard which would install better drivers. From our small sample size of testers, it seemed to work. Now that we have more users, we are seeing that this workaround does not work for everyone.

I am now hosting updated SteamOS graphics drivers on AUR with NVIDIA and Intel support fully re-enabled. I will have a winesapOS 3.1.0 alpha release soon with that change to see if that helps you.

**Comment by LukeShortCloud** [comment]
@chenxi050402 We have a new alpha release that should fix support for the GPD Win Max (and other devices with Intel graphics). Could you try this build and see if this is able to boot properly on your device?

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-alpha.0

**Comment by LukeShortCloud** [comment]
We now have a beta release with these updates rolled in if you want to try that instead: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-beta.0

**Comment by mjkl-gh** [comment]
I think I'm suffering from the same issue on a gpd win 3 (intel i7-1165g7)

When I boot from USB it will show grub, but the scaling or resolutions seems off. After choosing an option nothing happens. If I press a button again it will drop me back into uefi bios

All other SteamOS ISO's seem to work for me (HoloISO or booting vanilla SteamOS recovery image)

**Comment by LukeShortCloud** [comment]
@mjkl-gh Thanks for the bug report! What version of winesapOS are you using?

This sounds very similar to this bug we ran into which ended up being a screen resolution problem with our GRUB theme: https://github.com/LukeShortCloud/winesapOS/issues/302

**Comment by mjkl-gh** [comment]
> @mjkl-gh Thanks for the bug report! What version of winesapOS are you using?

[3.1.0-beta.0](https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-beta.0)
 
> This sounds very similar to this bug we ran into which ended up being a screen resolution problem with our GRUB theme: #302

It does indeed. Probably since the gpd devices use portrait screens from phones, something weird happens.

What is the easiest way to fix #302 in my case? I guess creating a custom iso in a VM? since I can't boot the iso, I can't update grub

**Comment by LukeShortCloud** [comment]
What orientation is the GRUB menu? Does it look normal or do you have to rotate the device by 90 degrees? Looking at the specs of the GPD Win Max in particular, it has a resolution of 1280x800. Our default GRUB resolution is much higher than that at 1600x1200. I was hoping GRUB would intelligently resize itself based on the supported resolution as we have many resolutions set but that does not seem to be the case.

It sounds like our original problem was that the resolution was too small. Now our resolution is too high. Let me get a build together with the GRUB theme set at ~720p. I also finally just got a Steam Deck so I can try to replicate the issue on there.

**Comment by LukeShortCloud** [comment]
Okay, I cannot replicate the issue on my Steam Deck. The resolution/scaling looks really weird, though (likely what you are also seeing). Not sure if we can easily fix how it looks. Even still, I suspect that on certain devices (such as on GPD devices) GRUB cannot automatically determine the correct resolution leading to an unbootable system in your case which is what I'm more concerned about. I'm working on a possible fix now.

**Comment by LukeShortCloud** [comment]
The original GPD Win has a resolution of 1280x720 so we will target that.

https://en.wikipedia.org/wiki/GPD_Win

**Comment by LukeShortCloud** [comment]
@mjkl-gh We have a new beta release for you to try. Let us know how this one works for you.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-beta.1

**Comment by mjkl-gh** [comment]
> @mjkl-gh We have a new beta release for you to try. Let us know how this one works for you.
> 
> https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-beta.1

Unfortunately it seems to do the exact same thing. 

I only tested it in Ventoy this time, but I got thrown back to grub (not uefi bios this time, probably due to using ventoy) on every option. 

I've spun up a VM on my homeserver and forked the repo to make some custom builds to see what works. I've left it overnight to run install for the first time (Compiling zfs and such takes quite some time)

First I will try with the theme disabled then grubFX 720x1280 (it's a portrait screen) to see if that will work

Maybe I should open a new Issue, this might be diverging from the OP's issue.

**Comment by mjkl-gh** [comment]
I've managed to create a couple of images.

First one I commented anything related to grubfx in the instal.sh. But it finished far too soon and didn't boot

Second was with grubfx changed to 720x1280. It took quite some time to install (compiling zfs and all) Didn't work

I've now commented anything related to grubfx in /etc/default/grub. It does seem to boot. However it is unable to find the device UUID and drops into rootfs shell. I think this might be related to ventoy? I will try again. with balenaetcher and a fresh USB

**Comment by mjkl-gh** [comment]
Just booted into winesapOS, it's showing the login screen. The problem with the UUID was probably to do with ventoy

**Comment by LukeShortCloud** [comment]
Glad you got it working and thanks for going out of your way to build and help test it out!

Short-term, I'll add documentation that Ventoy is not supported. Long-term, we can investigate adding official support for it.

Here are somewhat related GitHub issues:

- https://github.com/LukeShortCloud/winesapOS/issues/316
- https://github.com/LukeShortCloud/winesapOS/issues/370

**Comment by LukeShortCloud** [comment]
I'll also keep the 720p GRUB patch as that does fix formatting issues on my Steam Deck.

**Comment by LukeShortCloud** [comment]
@chenxi050402 @mjkl-gh Our stable winesapOS 3.1.0 is out now with fixes for this if you want to give it a try again.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0

**Comment by mjkl-gh** [comment]
Unfortunately no,

I see now I was not very clear in my last message. 

To be able to boot i commented multiple lines inside /etc/default/grub

One of which was 

`#GRUB_GFXPAYLOAD_LINUX=keep`

But also
```
#GRUB_GFXMODE=720x1280,auto
#GRUB_THEME=/boot/grub/themes/SteamBP/theme.txt
```

I think it's the GFXPAYLOAD causing the issue. But I didn't have time to test just that.

**Comment by LukeShortCloud** [comment]
@mjkl-gh @chenxi050402 Here is an even easier way to test a new theme. Copy and paste these commands into the "Konsole" terminal emulator app to setup the Vimix theme for GRUB:

```
sudo pacman -S --noconfirm grub-theme-vimix
sudo sed -i s'/.*GRUB_THEME=.*/GRUB_THEME=GRUB_THEME=\/usr\/share\/grub\/themes\/Vimix\/theme.txt/'g /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
```

Let me know if this works better than the Steam Big Picture theme for GRUB.

**Comment by mjkl-gh** [comment]
Will try when I get home. 

One more caveat. I was judging too quickly when testing,

```
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_GFXMODE=720x1280,auto
#GRUB_THEME=/boot/grub/themes/SteamBP/theme.txt
```
Does make it able to boot. However after loading the ramdisk the screen goes blank. Very similar to what happens if I try HoloISO in gamescope mode.

Will need to test further to see if Disabling GFXPAYLOAD or GFXMODE fixes that or if this is unrelated

**Comment by LukeShortCloud** [comment]
I've been reading more about the `GRUB_GFXPAYLOAD_LINUX` option. I am not sure why it is set to `keep` (we do not configure it so it appears to be a default from Arch Linux [we do not use GRUB from SteamOS because it is designed specifically for the Steam Deck and their read-only A/B partition layout]). The official documentation seems to suggest that setting it to `text` will work better for legacy BIOS systems. With that being said, I've also had this boot issue reported on the Steam Deck which only supports UEFI boot.

Here are some interesting findings when setting `GRUB_GFXPAYLOAD_LINUX=text`. This actually breaks the Steam Big Picture theme in my development virtual machine. Selecting anything in the GRUB boot menu kicks me out and takes me to the system UEFI screen. I've tried switching the theme to Vimix instead and it actually works great either way (with `keep` or `text` set). I am inclined to still say this is a problem with the Steam Big Picture mode theme.

https://www.gnu.org/software/grub/manual/grub/html_node/gfxpayload.html

**Comment by LukeShortCloud** [comment]
This package from Ubuntu sheds more light onto the situation. I'm not sure if Arch Linux has a package similar to this. Setting `GRUB_GFXPAYLOAD_LINUX=text` is definitely something we can do as it is an easy workaround. It also deals with graphics devices that are not in the blocklist but may have issues. That breaks our current theme so we'll also have to switch to the Vimix theme.

```
The 'set gfxpayload=keep' facility in GRUB provides smooth graphical
 handover to the Linux kernel. Unfortunately, this does not work on all
 systems, resulting in a black or corrupt display. This package provides a
 blacklist of PCI IDs which fail.
```

https://launchpad.net/ubuntu/xenial/+package/grub-gfxpayload-lists

**Comment by LukeShortCloud** [comment]
I was finally able to replicate the issue myself! I was originally testing winesapOS on my Steam Deck off of an external SSD, not the internal microSD card. Switching the GRUB theme to Vimix and setting the GFX payload definitely fixes it. I'll work on pushing a 3.1.1 patch release soon that addresses this. It should fix problems with all other devices, too.

**Comment by LukeShortCloud** [comment]
@mjkl-gh 3.1.1 is out now to address boot issues! https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.1

**Comment by LukeShortCloud** [comment]
@mjkl-gh winesapOS _finally_ supports Ventoy!

https://github.com/winesapOS/winesapOS/releases/tag/4.2.0

**Comment by mjkl-gh** [comment]
Many thanks for your work @LukeShortCloud. Unfortunately I don't own the device I originally tested this one anymore. But supporting Ventoy sounds like a great acomplishment for winesapOS. Once i finish the remodel of my house (are they ever finished?) I will revisit this.
