### ISSUE TITLE
Support the Steam Deck controller

### ISSUE THREAD

**Issue by liberodark** [LukeShortCloud/winesapOS#330]
Hi,

Im actually try to finish support of Steam Deck on Batocera.
But have issue from controller.

Have create udev rules for test : KO

```
#Steam Deck
SUBSYSTEM=="input", ATTRS{name}=="Valve Software Steam Controller", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"
ACTION=="add", ATTRS{idVendor}=="28de", ATTRS{idProduct}=="1205", RUN+="/sbin/modprobe xpad", RUN+="/bin/bash -c 'echo 28de 1205 > /sys/bus/usb/drivers/xpad/new_id'"
```

Have create xpad patch for test : KO

https://github.com/batocera-linux/batocera.linux/blob/d2fa6666fdaa2ba9a90aa89db8d29089be1efc64/package/batocera/controllers/xpad-noone/001-add-additional-xbox360.patch

Also im using steamdeck driver + kernel 5.17.x
PS : Batocera is based on Buildroot.
Maybe there is something specific I haven't seen...
If you have any idea about this ?

Best Regards

**Comment by LukeShortCloud** [comment]
Are you trying to get the Steam Deck controller itself to work? I do not have a Steam Deck to test with. According to some community research and my order time, I should finally get my confirmation email tomorrow. All my reverse-engineering of SteamOS so far has been done via their recovery image.

I do have a couple of ideas:

(1) SteamOS ships a few packages for extra controller support. It could be one of those. For example, refer to our open issue to add more controller support: https://github.com/LukeShortCloud/winesapOS/issues/222#issuecomment-1060154641

(2) It could be extra support built into their Linux Neptune kernel. Is Batocera Linux based on Arch Linux by chance? I have an AUR package `linux-steamos` you can easily install and try. Otherwise, I have the source code hosted on GitHub so you can compile it manually: https://github.com/LukeShortCloud/steamos-linux-neptune

By the way, you've got an awesome project! Glad to share knowledge wherever possible. 🙂

**Comment by liberodark** [comment]
Hi,

Im linking the issue of batocera in this question for more information : 
https://github.com/batocera-linux/batocera.linux/issues/5813

Best Regards

**Comment by LukeShortCloud** [comment]
Thanks for sharing that GitHub issue for more context! That's helpful. My Steam Deck is arriving this weekend so I can do hands-on testing soon. I'll let you know if I can figure anything new out.

**Comment by LukeShortCloud** [comment]
@liberodark I haven't tested this on my Steam Deck with winesapOS yet, but here are some observations I made while using the official SteamOS on my Steam Deck.

1. The controller never worked without the Steam client logged in and running.
2. Using Steam Picture mode (not the new Steam Deck Game Mode interface) on the desktop, I found how controllers work on the desktop. By default in SteamOS, it is in mouse and keyboard mode. I had to manually change this to controller mode to get it to work in some non-Steam (Lutris) games.
    - https://github.com/LukeShortCloud/rootpages/issues/764

**Comment by liberodark** [comment]
Hi @LukeShortCloud 
Thank you for your information i think is using API from steam for map controller.

Best Regards

**Comment by LukeShortCloud** [comment]
It looks like the controller will be natively supported in Linux 6.3: https://www.phoronix.com/news/Steam-HID-Steam-Deck-Linux-6.3

**Comment by LukeShortCloud** [comment]
I tested with Linux 6.3 and confirmed controller support works.

The relevant patches have not been backported to Linux LTS 6.1.

The OpenSD project looks like it may be able to help get the hardware working better on older kernel versions:

* https://gitlab.com/open-sd/opensd
* https://aur.archlinux.org/packages/opensd-git

**Comment by LukeShortCloud** [comment]
Test results:

* linux (6.3) = controller does work
* linux-lts (6.1) = controller does NOT work
* linux-steamos (5.13) = controller does NOT work

Installing `opensd-git` did not seem to change anything but I noticed that it added improved sound driver tweaks and lots of other changes. Probably worth installing automatically (alongside `linux`) if we detect Steam Deck hardware.
