### ISSUE TITLE
How to download software? Discover does not work.

### ISSUE THREAD

**Issue by agentwolf88** [LukeShortCloud/winesapOS#364]
How can i download or update software? Discover  crashs every time. Is there a alternativ package manager?

**Comment by LukeShortCloud** [comment]
@agentwolf88 What version of winesapOS are you using? Are there any error messages from Discover you can share?

Yes, we do provide an alternative package manager. The "Add/Remove Software" desktop shortcut opens up the Pamac package manager. It will manage Pacman, AUR, Flatpak, and Snap packages. If you run into any issues with that, the "winesapOS Upgrade" desktop shortcut will fix a known issue with Pamac. Note that Pamac is different from "Discover" which you can find by searching in the start menu.

**Comment by agentwolf88** [comment]
I have tryed 3.1.0-alpha.0 and 3.1.0-beta.0. In this versions is discover crashing.

**Comment by agentwolf88** [comment]
The error is...

plasma-discover PID: 11121 Signal: Segmentation fault (11)

**Comment by LukeShortCloud** [comment]
Thank you for providing your winesapOS version and error message! That is very helpful.

A quick search around shows that that exact error can be caused by many different things. Most related to your problem, I found this Reddit thread from 3 months ago talking about a similar error on a Steam Deck. They said they believed the problem to be related to package signature issues. https://www.reddit.com/r/linuxquestions/comments/t7j65w/problem_with_the_discover_app_on_linux_steam_deck/

For transparency, we have never tested Discover. It automatically gets installed as a dependency of KDE Plasma. I recommend using Pamac for now but there is no reason why we cannot fully support Discover.

I tried loading Discover on a winesapOS 3.0.0 installation and I got a different error relating to free disk space. The error messages are misleading because (1) I have about plenty of free space on both the root and home partitions and (2) my Internet connection is working as expected.

```
While pulling appstream2/x86_64 from remote flathub: Writing content object: min-free-space-size 500MB would be exceeded, at least 4.1 kB requested
```

```
Unable to load applications
Please verify Internet connectivity
```

We will look into this further.

**Comment by agentwolf88** [comment]
After an "upgrade Winesapos" Discover start. But now there is the bug with "no diskspace". XD

"Add/Remove Software" does not work for me. When i click on it, there will nothing happens. (no errors)

**Comment by LukeShortCloud** [comment]
lol At least we're getting the same error now. I wonder why an upgrade would fix the segmentation fault. All the packages are the same especially with the latest beta it should have the newest packages.

Interesting that Pamac silently fails. I'll check into that, too.

**Comment by LukeShortCloud** [comment]
@agentwolf88 Our stable winesapOS 3.1.0 is out now with fixes for this if you want to give it a try again. If you're running an old version of winesapOS, just use the "winesapOS Upgrade" desktop shortcut to update your system.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0
