### ISSUE TITLE
winesapOS runs out of disk space on 32GB USB flash drive

### ISSUE THREAD

**Issue by SegaGameBoyStation** [LukeShortCloud/winesapOS#369]
I am trying to get SteamOS 3 on my PC with not much sucess.
I tried this OS flashed via Balena Etcher and while it boots intially, when trying to install the GPU drivers via the first time setup script, I get an error about one of the driver packages being too large to download.
This ends up with freezes and eventually the plasma session crashes and won\t recover.
Then the system becomes unresposive and even open programs don't work.
I can change tty but that's about it.

**Comment by LukeShortCloud** [comment]
Running out of disk space will certainly cause lots of issues. It sounds like the root file system is not being resized.

Could you provide the log output from our resize service? Details on how to get that can be found here:

https://github.com/LukeShortCloud/winesapOS#root-file-system-resizing

Also, what exact version of winesapOS are you using: 3.0.1 stable or 3.1.0-beta.1?

**Comment by LukeShortCloud** [comment]
In the past, we ran into an issue where NVMe drives did not work with our root file system resize script. That was fixed in 3.0.1 stable and tracked here: https://github.com/LukeShortCloud/winesapOS/issues/252

If your drive is not a USB, SATA, or NVMe drive, there may be missing logic we need to add. For example, SCSI and IDE drives use a different naming convention that we currently do not account for. Now that I think about it, we do not check for SD cards either.

@SegaGameBoyStation Could you provide the output of these two commands?

```
mount
```

```
lsblk
```

**Comment by SegaGameBoyStation** [comment]
It was a 32GiB USB stick as that is what I have available, my PC is just one of those tiny mini PC APU systems so all drives are taken up.
I will redo it and post back around Monday or Tuesday.

**Comment by A-mak88** [comment]
I am also experiencing strange behavior after first time setup.

Running a dell wyse thin client 7020 (amd E8400 graphics) with the os on a 64gb usb using Rufus on win10 to flash the image to the usb.

I'm doing my 3rd format at the moment, earlier it ran the first time setup and the GUI froze (but the mouse was still working), ctrl+alt+del didnt work and neither did pressing the power button (I ended up having to hold for cold shutdown). Upon the next boot it froze just after initializing ramdisk, the 1st time I wasn't sure what the upgrade shortcut did so I ran that and have the same issue but could hear what I assume is thrashing of the USB. I did set swap-space to 4gb (with 4gb of ram installed, I have some more sticks laying around I plan to put in once I find one). The boot freeze happens regardless of what kernal I choose.

Almost finished the current format to USB, going to give it another try. I didn't notice any errors but I was not paying attention to the CLI. (I will this time)

If there is anything you'd like me to try, please advise.

**Comment by A-mak88** [comment]
@LukeShortCloud not sure if you have seen my post (apologies if you have not), If you have, I have now heavily edited it and narrowed down where the issue occurs as much as possible.

Please let me know if there's anything you'd like me to try, also I apologize if I'm supposed to open my own issue thread; I'm not experienced at github.

**Comment by LukeShortCloud** [comment]
@A-mak88 Thanks for your help narrowing down that issue! Since it seems unrelated to this, I opened up a separate GitHub issue for us to continue troubleshooting your problem there: https://github.com/LukeShortCloud/winesapOS/issues/372 .

@SegaGameBoyStation A 32 GB flash drive would lead to these issues. Short-term, we will update our documentation to increase the minimum requirements. Once additional packages are installed and swap is configured then the system definitely will max out its size at 32 GB. We have made a lot of great strides to reduce the size of the image. Unfortunately, the switch to using Flatpaks has made us use more storage space again which brings us back to where we started. The good new is that we are working on a minimal image that will require only around 8 GB of space. Related issues:

- https://github.com/LukeShortCloud/winesapOS/issues/317
- https://github.com/LukeShortCloud/winesapOS/issues/300
- https://github.com/LukeShortCloud/winesapOS/issues/254
