### ISSUE TITLE
Clone winesapOS already setup on USB to a SSD

### ISSUE THREAD

**Issue by tooelitepete** [LukeShortCloud/winesapOS#390]
Can I just use gparted and copy/paste all the partitions from the USB (that's completely setup) to my spare SSD?
It copies the uuids too.

**Comment by LukeShortCloud** [comment]
In theory, yes, that should work. We also use labels (where possible) for mounts to avoid issues with UUIDs being potentially different.

The steps to move it safely would be to:

(1) Clone your entire USB to your SSD.
(2) Boot up winesapOS from the SSD. Re-enable the `winesapos-resize-root-file-system` service with this command: `sudo systemctl enable winesapos-resize-root-file-system`. Then reboot for the root file system to fill up 100% of the available disk space.

Let me know if that works for you as I haven't tried this use-case before and am curious!

**Comment by tooelitepete** [comment]
@LukeShortCloud it works...but only if you copy and paste the partitions from a non-setup USB. So straight after flashing to USB, you copy/paste the partitions and then it works.
Doing it with a completely setup USB gives errors of failed to mount /home.

**Comment by LukeShortCloud** [comment]
Interesting, that is good to know. Cloning any operating system can be tricky. At least we now know that there may be issues with the `/home/` directory in our case.

**Comment by tooelitepete** [comment]
NO LONGER WORKING!
It just takes me into grub_rescue. Pissing me off

**Comment by LukeShortCloud** [comment]
Is the GRUB error (1) when booting winesapOS from your USB drive for the first time or (2) after you copied it to the SSD and then boot from the SSD?

Assuming situation 2, if you keep the USB drive plugged in that can cause issues since the labels and UUIDs are the same. This confuses GRUB and `mount`. I've encountered this myself where some partitions mount from my SSD but others may mount from the USB drive. Long-term, I plan to provide a script to rename the labels and regenerate the UUIDs to help. For now, we have some documentation at least around the labels: https://github.com/LukeShortCloud/winesapOS#two-or-more-set-ups-of-winesapos-cause-an-unbootable-system . Make sure the USB drive is unplugged for now.

This weekend, I'm aiming to release our first public minimal image that will be 7 GiB in size. It will be an alpha development release. Not sure if that will help your exact problem right now but it will make downloading and transferring the image over faster. The first-time setup will allow you to install all of the typical tools and game launchers you want from a checklist.

**Comment by tooelitepete** [comment]
@LukeShortCloud (2). When I boot from SSD.
It says unknown filesystem and takes me to grub_rescue.
The USB has been disconnected.

**Comment by LukeShortCloud** [comment]
Thanks for confirming! I'll see if I can replicate the issue.

**Comment by tooelitepete** [comment]
@LukeShortCloud any update/fix?

**Comment by tooelitepete** [comment]
@LukeShortCloud no matter what I do I can't get it to work. I suspect it's a grub bootloader issue.
I'm awfully close to giving up on the project entirely.

**Comment by LukeShortCloud** [comment]
This was never an intended use-case and I'd be more than happy to help out more. I won't have time to work on this until later this week. Figuring out what the exact problem is and fixing it takes times.

I recently released our first minimal image (release notes coming soon). Try this as an alternative:

1. Setup the minimal image on a USB drive.
2. Copy or, after booting into the USB drive, download your preferred image to the USB drive.
3. Use `dd` or Balena Etcher (use `pacman -S balena-etcher` to install) to put the image on the SSD.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.0-alpha.0

**Comment by tooelitepete** [comment]
@LukeShortCloud balena etcher will only let me flash to an external storage device, not ssd. And I've already tried the minimal image.

**Comment by LukeShortCloud** [comment]
In Balena Etcher, when you "Select target" there is an option to "Show hidden" storage devices. It will let you flash an image to any drive except the one its physically running on (the USB drive, in this case).

**Comment by LukeShortCloud** [comment]
@tooelitepete Does the solution to use hidden storage devices within Balena Etcher work?

I looked up various guides for cloning disks using GParted. It looks like it only supports copying over partitions and not cloning one drive to another. This means it will not copy the full GRUB installation on the beginning of the storage device (it is just before the first partition). Here's a guide that has some hints about re-installing GRUB to the new drive:

http://ridz1ba.blogspot.com/2015/11/how-to-clone-hdd-or-sdd-using-gparted.html

Overall, I would not recommend using GParted for this. If you are comfortable with the CLI, the `dd` command works perfectly since it does a full 1:1 copy. This worked for me:

```
lsblk
sudo dd if=/dev/<FLASH_DRIVE> of=/dev/<SSD> bs=1M
```

Otherwise, Balena Etcher should work as a GUI solution.

**Comment by LukeShortCloud** [comment]
I'm going to add documentation based on everything we discussed here along with hints on how to use GParted. However, we will not officially support GParted because of the added complexity.
