### ISSUE TITLE
[setup] Surface Book Touch Screen non-functional  

### ISSUE THREAD

**Issue by NNickey** [LukeShortCloud/winesapOS#539]
https://linux-hardware.org/?probe=7ac23d772f

Unable to use the touchscreen using Performance build, no response to any touch. Do not have the Surface Pen to test with.

**Comment by LukeShortCloud** [comment]
@NNickey Thanks for reporting this! Does the touchscreen work on other Linux distributions? Does booting into the "Linux LTS" kernel (instead of "Linux SteamOS") help?

**Comment by LukeShortCloud** [comment]
@NNickey I found these instructions for installing a Linux kernel that has all of the drivers required for various Microsoft Surface devices. Give this a try and let me know if it works for you.

https://github.com/linux-surface/linux-surface/wiki/Package-Repositories#arch-linux-repository

**Comment by LukeShortCloud** [comment]
That link I sent is actually only for setting up the repository. Here is how to setup the repository and also install the special Linux kernel:

https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#arch

**Comment by NNickey** [comment]
Trying this out right now, will edit on finish. Touch did work on PopOS from USB, and having to wait for the winesapOS update because it's failing on a steamos library and can't run `sudo pacman -Syu` because of `steamdeck-packages.steamos.cloud` returning 404. Latest issue I saw say that you updated the package names and doesn't hurt to be sure everything is up to date.

**Comment by LukeShortCloud** [comment]
@NNickey Valve recently changed their repository names which broke all upstream forks of SteamOS including winesapOS. Here's the workaround:

```
sudo sed -i s'/\[holo\]/\[holo-rel\]/'g /etc/pacman.conf
sudo sed -i s'/\[jupiter\]/\[jupiter-rel\]/'g /etc/pacman.conf
sudo pacman -S -y -y
```

That's interesting that the touchscreen works on PopOS. I'll have to compare the Linux kernel and see if there are patches we can use. I suspect the problem is that the "Linux SteamOS" kernel is too old. "Linux LTS" has a better chance of working but it's currently stuck on 5.15 (and not the new 6.1) in Arch Linux.

**Comment by NNickey** [comment]
I've used holo-3.3.3 and jupiter-3.3, but I'll change those to -rel instead now.

Touch has finally started working,
scroll, pinch zoom, pinch zoom, track 10 points all work
after following all the steps from https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#arch for Arch and selecting 'surface' from the grub boot screen.

:+1:

**Comment by NNickey** [comment]
Seems that boot option for Linux doesn't support touch either, touch only works on linux-surface.

**Comment by LukeShortCloud** [comment]
Since Microsoft Surface devices boot fine (just without touchscreen support), we can automatically install the required dependencies during the first-time setup if a Microsoft Surface device is detected.

```
$ sudo dmidecode -s system-family
Surface
```

Full output of `dmidecode` from a Microsoft Surface 4: https://linux-hardware.org/?probe=761615ddb2&log=dmidecode

**Comment by LukeShortCloud** [comment]
@NNickey winesapOS 3.3.0 has been released with support for the Microsoft Surface devices. It will automatically detect if it is a Surface device and install the drivers during the first-time setup.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0
