### ISSUE TITLE
[install] Issue flashing MacBook Pro (2016) internal NVMe (booting)

### ISSUE THREAD

**Issue by loicloic** [LukeShortCloud/winesapOS#544]
I've put the MacBook in target disk mode and used Balena Etcher to flash the image to it, it doesn't show as a boot device nor boot (Option key at boot). I also tried dd'ing to the same result. 

I've successfully booted from a mass storage so I also tried using Balena Ether from within winesapOS to flash the image to the NVMe. same result.

What am I doing wrong here ?

**Comment by LukeShortCloud** [comment]
Thanks for reporting this issue, @loicloic ! I've only tried winesapOS on internal drives on non-Mac desktops and laptops. The only Mac I have is for work so I can't wipe the internal drive. I'll do some research online and see if there are any known issues with Linux being setup like this on a Mac.

**Comment by LukeShortCloud** [comment]
@loicloic What model and year MacBook do you have?

I suspect the problem is that newer Macs with the T2 security chip require special drivers to access much of the underlying hardware (including the NVMe drive). It's a possible situation where Linux bootloader can't even access or understand what internal storage is available yet. The bootloader is essentially lost. That's my current theory, anyways.

**Comment by loicloic** [comment]
@LukeShortCloud it’s not  T2 laptop. Model Number is A1707 hosting a T1 chip.

**Comment by LukeShortCloud** [comment]
@loicloic Thanks for confirming! My theory must be wrong then and we can at least rule out the T2 chip being a problem. The T1 chip is way less invasive and should have better native Linux support.

**Comment by loicloic** [comment]
@LukeShortCloud you’re welcome. Just to reiterate a point am I made above if I boot from  external I can then see and flash the NVMe. I don’t know enough about the linux boot process / initramfs but this seems to be “missing” the drivers to access the NVMe because “a full kernel” can see it as mentioned.

**Comment by LukeShortCloud** [comment]
Yeah, I've been able to successfully test booting from an external USB device on a wide range of Mac hardware in the past. I'm not sure how to workaround the internal storage issues. It seems like a "chicken or the egg" kind of problem.

**Comment by LukeShortCloud** [comment]
rEFInd may be the actual solution we need. It's a bootloader that helps to boot standard UEFI operating systems (i.e., Linux and Windows) on a Mac.

https://www.rodsbooks.com/refind/

The problem is that installing winesapOS would wipe out that bootloader if it's installed. This likely depends on us finishing having a live image installer.

https://github.com/LukeShortCloud/winesapOS/issues/370

**Comment by loicloic** [comment]
Indeed. Been using rEFInd for a while and I think you're right with the issue 
being the peculiar way winesapOS installs. 

Hope #370 is the way to fix this. Thanks for keeping an eye on this issue!

**Comment by LukeShortCloud** [comment]
The biggest blocker at this point is that I need to get a personal MacBook Pro to try this on. I'm happy to try to get this to work!

**Comment by LukeShortCloud** [comment]
Here are some good hints. These are the key takeaways for me:

- Partitions on Macs should have gaps between them as Apple sometimes changes the alignment. The guide below recommends a 128 MB gap.
- The last and large partition in macOS needs to be shrunk. The free space is used as the root and home partition (using LVM volumes, Btrfs subvolumes, etc.). Alternatively, we could make as many partitions as we want but only one is required.
- The only other partition we need is the UEFI partition which should be the first partition. Mount that to `/boot/` and do a normal install with GRUB or systemd-boot.

https://0xadada.pub/2016/03/05/install-encrypted-arch-linux-on-apple-macbook-pro/

I still need to get my hands on an Intel Mac before I can automate all this.

**Comment by LukeShortCloud** [comment]
Here's how to have Linux boot by default instead of macOS:

```
When OSX loaded. Using Disk Utility to format /dev/sda3 (128MB HFS+ we have created before) with Journaled format.

Then create this file structure:

|___mach_kernel   
|___System   
    |___Library   
        |___CoreServices   
            |___SystemVersion.plist   
            |___boot.efi              (Is the file we'v copy, upload in the previous step)   

Edit SystemVersion.plist content:

<xml version="1.0" encoding="utf-8"?>
<plist version="1.0">
<dict>
    <key>ProductBuildVersion</key>
    <string></string>
    <key>ProductName</key>
    <string>Linux</string>
    <key>ProductVersion</key>
    <string>Arch Linux</string>
</dict>
</plist>

To make arch auto boot with out holding alt/option, run this command:

sudo bless --device /dev/disk0s4 --setBoot
```

https://github.com/kyoz/mac-arch#make-arch-duo-bootable

**Comment by LukeShortCloud** [comment]
I found more context about this `bless` command. It basically removes the need to install and use rEFIt or rEFInd.

https://bbs.archlinux.org/viewtopic.php?id=275322
https://wiki.archlinux.org/title/mac#Using_blessing

**Comment by LukeShortCloud** [comment]
I bought a cheap non-T2 Mac for testing. I hope to able to test and replicate this issue in the near future.

**Comment by LukeShortCloud** [comment]
Here is another good guide I will try out: https://linuxnewbieguide.org/how-to-install-linux-on-a-macintosh-computer/

**Comment by GuestSneezeOSDev** [comment]
what type of mac and version of winesapos are you using since there could be a chance of a kernel error

**Comment by LukeShortCloud** [comment]
I did a quick test on my MacBook Air (2015?) with the latest development build. It fixes all remaining hardware incompatibles on the PC side. However, the Mac still does not boot. I have been reading that rEFInd is required to boot most Linux distributions. I'll try that next.

I've also been testing out dual-boot with macOS. It's tricky because the UEFI partition is too small (300 MiB and it's almost full). Apple knows exactly how much space they need so they do not bother with leaving extra space for other operating systems. Using GParted in Linux, I was able to resize and move partitions around to increase the UEFI partition. There were a lot of scary errors but it did work. By work I mean macOS would boot. winesapOS still would not. Even more reason why I believe rEFInd is needed.

**Comment by LukeShortCloud** [comment]
Here is the current work-in-progress guide for macOS dual-boot. It does NOT work so please do not follow it!

https://github.com/LukeShortCloud/winesapOS/tree/4caf1d012864c7810ffe3baa5ae879cc9a202777?tab=readme-ov-file#dual-boot

**Comment by LukeShortCloud** [comment]
@loicloic I got winesapOS working on my internal Mac drive! The short answer is that you need rEFInd and you have to dual-boot.

The long answer is that it is a bit complicated but all of the steps have been documented here: https://github.com/LukeShortCloud/winesapOS/tree/862ee45f24d2c63d90a557473053826a41ca1f56?tab=readme-ov-file#dual-boot

@GuestSneezeOSDev has been helping to automate that (thank you, by the way!) so hopefully this will be an easier process soon. I just need to review their scripts and see if we can get them upstream into winesapOS.

You will need to use at least winesapOS version 4.1.0-beta.0 which adds initial dual-boot support: https://winesapos.lukeshort.cloud/repo/iso/winesapos-4.1.0/_test/
