### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by mundusnine** [LukeShortCloud/winesapOS#545]
I originally had that [issue](https://github.com/LukeShortCloud/winesapOS/issues/537), I worked around it by changing the names of the packages in the update script by making a [custom one](https://gist.github.com/mundusnine/9d7e16479a68de9b250b9051618bb855). The changes in the script are I renamed the repos/links to point to the -rel repos.

Now my issue is that SSL certificate for winesapos.db is borked ? I am unsure if it's my fault.

![image](https://user-images.githubusercontent.com/29337013/211849350-3ad9dd5e-2cea-4eb2-a4be-aed185f0c937.png)

**Comment by mundusnine** [comment]
Euhm, when trying to go to your website I get:
![image](https://user-images.githubusercontent.com/29337013/211850715-3717c51d-692b-4f14-8920-3bbe95c0f207.png)

So your website is down @LukeShortCloud

**Comment by LukeShortCloud** [comment]
Hey @mundusnine , thanks for bringing this to my attention! Can you try running `pacman -S -y -y` again to see if there are still any issues?

The reason this happened was because the repository is hosted on a single server and it was forcefully rebooted by my hosting provider. I will do two things: (1) work with them to understand why they rebooted my server and (2) update my web services to better handle reboots. I used to have the repository be highly available across 3 nodes but we didn't have enough funding to keep those other 2 servers.

I actually can and do route traffic to different web services based on (1) domain name and, separately, (2) URL path. `lukeshort.cloud` is not used for hosting the repository nor is `winesapos.lukeshort.cloud`. I host it on `winesapos.lukeshort.cloud/repo/` which also does not show directory listings for security reasons (if it works correctly, it will say "403 Forbidden"). You can verify this works by downloading a package directly from it:

```
$ wget https://winesapos.lukeshort.cloud/repo/winesapos/x86_64/zerotier-gui-git-1.3.0.r84.44626a5-1-any.pkg.tar.zst
```

I've also already updated our "winesapOS Upgrade" script to deal with the new repository names but it has not been pushed up to the "stable" branch which is why it is not being applied currently. You can modify the files in `~/.winesapos/` to use the "main" branch instead. Either way, you seem to have it handled via your modified upgrade script. :-)

Hope this helps to clarify a bit about our repository infrastructure. Please let me know if the repository is working for you now.

**Comment by mundusnine** [comment]
I did the command you asked, `pacman -S -y -y`, and there were no issues. The repository seems to be working fine now. Thank you again for your help and for your hard work on the project.
