### ISSUE TITLE
Failed: Failed to start fan manager

### ISSUE THREAD

**Issue by ElecTriX666** [LukeShortCloud/winesapOS#562]
[FAILED] Failed to start A fan manager daemon for MacBook Pro.

-

After rebooting, after first initial setup, this comes up and keeps OS from booting.

I'm on a PC so? How do I fix this and why does this keep the OS from booting?

**Comment by LukeShortCloud** [comment]
@ElecTriX666 Thanks for reporting this! I hope we can get to the bottom of your problem.

That message is a false-positive. The fan service would have no affect on winesapOS booting. I have now opened a separate GitHub issue to only enable the service on Macs to prevent that error from appearing on PCs:

https://github.com/LukeShortCloud/winesapOS/issues/563

The failed boot after the initial setup can be from a number of reasons. It's usually driver related. A similar issue was reported from a person who had a old NVIDIA graphics card. We switch from the open source to proprietary driver during the initial setup since it is more powerful. But it lacks support for older cards.

https://github.com/LukeShortCloud/winesapOS/discussions/554
https://github.com/LukeShortCloud/winesapOS/issues/440

What kernel are you using? Try both Linux SteamOS and Linux LTS.

What specs does your computer have? Does it have a NVIDIA graphics card?

**Comment by ElecTriX666** [comment]
> @ElecTriX666 Thanks for reporting this! I hope we can get to the bottom of your problem.
> 
> That message is a false-positive. The fan service would have no affect on winesapOS booting. I have now opened a separate GitHub issue to only enable the service on Macs to prevent that error from appearing on PCs:
> 
> #563

Great idea.

> The failed boot after the initial setup can be from a number of reasons. It's usually driver related. A similar issue was reported from a person who had a old NVIDIA graphics card. We switch from the open source to proprietary driver during the initial setup since it is more powerful. But it lacks support for older cards.
> 
> #554 #440

Is it possible to skip this somehow?

> What kernel are you using? Try both Linux SteamOS and Linux LTS.

This is the weirdest thing. First time I booted it had 4 different alternatives. Now when I boot up I only have one. Linux LTS.

> What specs does your computer have? Does it have a NVIDIA graphics card?

Yes, and it is old.. A GTX 680.

**Comment by LukeShortCloud** [comment]
During the first-time setup, if you do not select a graphics driver and just select next/OK, it will continue on and do nothing. Alternatively, it's safe to pick with the AMD or Intel options in your case. Those just install additional packages useful for that hardware. However, the open source NVIDIA driver remains untouched and useable with the AMD and Intel options.

I'm not sure why there would be 4 Linux LTS options. It's supposed to be (1) Linux LTS, (2) Linux LTS fallback, (3) Linux SteamOS, and (4) Linux SteamOS fallback. Can you provide a screenshot of what you're seeing? If you use the up and down arrows on the GRUB menu it will stop the countdown to when it automatically boots. Then you can take a picture. Arch Linux just promoted `linux-lts` from 5.15 to 6.1 a few days ago so I wonder if that's related.

I'll make it a higher priority to support older NVIDIA graphics cards in our upcoming 3.3.0 release. We have gotten a lot of reports about that lately. I hate to see old hardware go to waste due to arbitrary software limitations. The good news is that Arch Linux still provides those old drivers so it's a matter of integrating that into our first-time setup.

**Comment by ElecTriX666** [comment]
> During the first-time setup, if you do not select a graphics driver and just select next/OK, it will continue on and do nothing. Alternatively, it's safe to pick with the AMD or Intel options in your case. Those just install additional packages useful for that hardware. However, the open source NVIDIA driver remains untouched and useable with the AMD and Intel options.

Perfect, thanks!

> I'm not sure why there would be 4 Linux LTS options. It's supposed to be (1) Linux LTS, (2) Linux LTS fallback, (3) Linux SteamOS, and (4) Linux SteamOS fallback. Can you provide a screenshot of what you're seeing? If you use the up and down arrows on the GRUB menu it will stop the countdown to when it automatically boots. Then you can take a picture. Arch Linux just promoted `linux-lts` from 5.15 to 6.1 a few days ago so I wonder if that's related.

![20230225_185332](https://user-images.githubusercontent.com/35463138/221372370-633b9d63-ace3-4111-841a-4453dc9ddacc.jpg)

As you can see, the text also gets cut off. This problem with cutoff is also at first boot.
 
> I'll make it a higher priority to support older NVIDIA graphics cards in our upcoming 3.3.0 release. We have gotten a lot of reports about that lately. I hate to see old hardware go to waste due to arbitrary software limitations. The good news is that Arch Linux still provides those old drivers so it's a matter of integrating that into our first-time setup.

So just so I undrerstand, those old drivers are pre-installed before the first-time setup? Or can I install these manually?

**Comment by LukeShortCloud** [comment]
Thanks for providing that picture! When GRUB doesn't fully support a graphics card it takes a safe approach to default to a resolution it knows will work. If the resolution is unsupported, then GRUB could be unresponsive and the system can be unbootable. You can manually define the resolution of GRUB. Here is an example of how to use 1080p.

```
$ sudo vim /etc/default/grub
GRUB_GFXMODE=1920x1080
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
```

Our default configuration is `GRUB_GFXMODE 1280x720,auto` which uses a 720p display for common portable devices (Steam Deck, GPD Win Max, etc.). If it cannot render at that resolution, it tries to automatically figure out a good resolution. Usually this defaults to 640x480 if the GPU is not fully supported.

As it stands right now, you cannot see the entries but they should be as follows:

1. Linux LTS
2. Linux LTS fallback
3. Linux SteamOS
4. Linux SteamOS fallback
5. SteamOS snapshots

Linux LTS provides the best hardware compatibility, especially for NVIDIA devices. Fallback options includes more drivers and are only recommended if the non-fallback option does not work.

----

You can install the NVIDIA driver for your old card manually for now by opening up "Konsole" or "Terminator" and using this command:

```
$ yay -S nvidia-470xx-dkms
```

A reboot will be required when it finishes installing.

**Comment by ElecTriX666** [comment]
Changing GRUB_GFXMODE to 1920x1080 does no change.

After installing old Nvidia drivers and rebooting, I tried to start Steam Desktop. A box showing Steam updating for a second then.. Nothing. I assume Steam crashes.

**Comment by LukeShortCloud** [comment]
Thanks for reporting back.

Perhaps disabling the GRUB theme will help. You can edit the `/etc/default/grub` file and remove or comment out the line that starts with `GRUB_THEME`. Then re-generate the GRUB configuration.

```
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
```

Although NVIDIA drivers (including the old ones) shouldn't be using the Mesa drivers, your Steam issues sound like it's related to this:

https://github.com/LukeShortCloud/winesapOS/issues/565#issuecomment-1445261115

I'm working on a fix for it.

**Comment by LukeShortCloud** [comment]
@ElecTriX666 I have fixed an issue where Steam and a few other applications would not start. Try running these commands to update the Mesa graphics library and then reboot.

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

Let me know if that helps or not.
