### ISSUE TITLE
[upgrade] Installing erofs-utils breaks XZ

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#623]
Installing the `erofs-utils` package also updates `xz`. This is a big problem as GLIBC is not upgraded yet so XZ commands no longer work. Pacman packages use XZ compression so no new packages can be installed after this.

```
pacman: /usr/lib/libc.so.6: version 'GLIBC_2.34' not found (required by /usr/lib/liblzma.so.5)
```

**Comment by LukeShortCloud** [comment]
The current upgrade command is `/usr/bin/pacman --noconfirm -S --needed erofs-utils`. That means that that package has a hardcoded dependency on a newer version of XZ.

**Comment by LukeShortCloud** [comment]
This happens when upgrading from old operating systems. I encountered this with a test upgrade from winesapOS 3.0.1 to 3.3.0 that I did last night.

**Comment by LukeShortCloud** [comment]
The Arch Wiki recommends using `pacman-static` to deal with cases where Pacman is broken. We should default to using that for upgrades.

https://aur.archlinux.org/packages/pacman-static
https://wiki.archlinux.org/title/pacman

**Comment by LukeShortCloud** [comment]
The binary can be downloaded directly from here: `https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static`

Or as a PKG from here:

```
[pacman-static]
SigLevel = Required
Server = https://pkgbuild.com/~morganamilo/$repo/$arch
```

**Comment by Sebazzz** [comment]
Quick addition from my side:

- After upgrading winesapos I noticed sound not working anymore, and pacman not working
- This turned out to be the glibc problem
- I downloaded the pacman-static to update lib32-glibc, which restored pacman functionality
- To fix the broken packages, I run `pacman -Syyu` but the rackspace mirror which is set in `/etc/pacman.conf` seems to be broken because some of the qt5 packages return a 404 so I switch to one of the mirrors in the Arch mirrorlist

This seems to fix the issues and recover the sound also.

**Comment by Sebazzz** [comment]
llvm was also missing, causing software rendering to be invoked. Needed to install using `sudo pacman -S llvm15-libs`.

**Comment by Sebazzz** [comment]
llvm was also too new (v16) causing steam to crash, so I installed an older version via the arch archive.
