### ISSUE TITLE
Internal Drive is Unbootable with Legacy BIOS Boot

### ISSUE THREAD

**Issue by Dark98** [LukeShortCloud/winesapOS#627]
I'm attempting to install onto a HP Elitebook 8560w but it doesn't boot when I select the drive in BIOS boot mode.

The laptop support Experimental UEFI Support and boots when enabling this option, however this messes with a few things

**Comment by LukeShortCloud** [comment]
Hey @Dark98 , thanks for reporting your problem! What exact issues are you experiencing? winesapOS is built to support both legacy BIOS and UEFI. If you see a black screen, that may be related to a graphics driver issue in winesapOS 3.2.1. Try using 3.2.0 instead and see if that works.

**Comment by Dark98** [comment]
> Hey @Dark98 , thanks for reporting your problem! What exact issues are you experiencing? winesapOS is built to support both legacy BIOS and UEFI. If you see a black screen, that may be related to a graphics driver issue in winesapOS 3.2.1. Try using 3.2.0 instead and see if that works.

When I select the "Upgrade Bay" boot option (Where I have flashed winesapOS to) the system just tried booting from the next available media, but if I enable the Experimental UEFI mode, winesapOS boots completely fine

**Comment by LukeShortCloud** [comment]
What version of winesapOS (3.2.1?) and image type (minimal, performance, or secure?) are you using? I'll see if I can replicate the issue with legacy BIOS boot.

**Comment by Dark98** [comment]
Using the latest performance image

**Comment by LukeShortCloud** [comment]
Thanks for the update. I don't have a PC that supports legacy BIOS boot to test with. I tried running the winesapOS 3.2.1 performance image in a VM with legacy BIOS boot and that works fine with the image being emulated as an internal drive.

I have a new winesapOS 3.3.0 release coming out this weekend. Perhaps that will work better for you. It includes an updated GRUB boot loader that includes two years worth of new features and bug fixes.

**Comment by Dark98** [comment]
Okay, perfect, thank you🙏

I'm not 100% certain but I think it could be due to my Laptop not recognising the GPT Partition layout for internal devices when booting in the standard BIOS Boot Mode

**Comment by LukeShortCloud** [comment]
That's a good point, you could be right. Microsoft says that the BIOS needs to specifically support GPT for legacy BIOS boot but it does not sound like it is mandatory (since the old standard was MBR).

https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/switch-from-legacy-mbr-disk-to-gpt-disk-with-windows-10

All of the winesapOS 3.3.0 images recently finished uploading if you wanted to give that a try.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

**Comment by Dark98** [comment]
I'll try it within the next 24hours and update you :)

Would an MBR based image be possible if it doesn't work still? (For true Legacy Boot support)

**Comment by Dark98** [comment]
Unfortunately the lastest image has the same issues with my laptop 😥

**Comment by LukeShortCloud** [comment]
Darn, at least that can help us narrow it down. I'll keep this GitHub Issue open and update it if I ever find anything relevant.

**Comment by LukeShortCloud** [comment]
@Dark98 You could try converting the drive from GPT to MBR using the `gdisk` command. Perhaps that will help.

https://superuser.com/a/1252393

**Comment by Dark98** [comment]
> @Dark98 You could try converting the drive from GPT to MBR using the `gdisk` command. Perhaps that will help.
> 
> https://superuser.com/a/1252393

I tried a different method of converting the drive and it didn't resolve any issues

**Comment by LukeShortCloud** [comment]
Okay, good to know. Thank you for confirming!

**Comment by Frostswing** [comment]
i might have a similar issue
i flashed the os (the latest performance version as of today which is 3.3) and try to run the installation using USB.

the OS runs (showing the "arch Linux, with Linux linu" screen) and then after loading ramdisk my screen just goes black.

i do suspect it to be a graphics driver, but i don't know what can i do to solve it

i own a gtx 660 (old one...)

**Comment by Dark98** [comment]
> i might have a similar issue
> i flashed the os (the latest performance version as of today which is 3.3) and try to run the installation using USB.
> 
> the OS runs (showing the "arch Linux, with Linux linu" screen) and then after loading ramdisk my screen just goes black.
> 
> i do suspect it to be a graphics driver, but i don't know what can i do to solve it
> 
> i own a gtx 660 (old one...)
> 
> nvidia.modeset=0 doesn't work
> nomodeset and removing the quite shows that the last line that is running is "Started Accounts Service"
> but then it stuck on flickering "_"
> 
> i change the tty then i get shell, but no GUI...

This is a different/unrelated issue to mine, I don't even get to grub

**Comment by LukeShortCloud** [comment]
It turns out that converting the partition table from GPT to MBR breaks the GRUB bootloader.

Step 1 is to convert from GPT to MBR.

- `sudo gdisk /dev/vda` > r (enter recovery mode) > g (convert from GPT to MBR) > w (write changes) > Y (Yes to confirm)

https://superuser.com/questions/1250895/converting-between-gpt-and-mbr-hard-drive-without-losing-data

Step 2 is to re-install the GRUB bootloader:

```
mount /dev/vda4 -o subvol=/ /mnt
mount /dev/vda3 /mnt/boot
mount --bind /dev /mnt/dev
mount --bind /proc /mnt/proc
mount --bind /sys /mnt/sys
chroot / grub-install --target=i386-pc /dev/vda
```

This all assumes that you are booted into an Arch Linux ISO with the winesapOS minimal image attached at `/dev/vda`.

I can confirm that this is working in my legacy BIOS boot VM but it does not work on physical hardware (I recently picked up a cheap old Windows XP era PC to test with). I'll need to keep investigating this.

**Comment by LukeShortCloud** [comment]
Weird. The official Arch Linux ISO doesn't even work for me. I'm using a system with a 64-bit AMD Athlon 4800 CPU. This might be an upstream issue with Arch Linux but I can't see any reasons for this (ex., the x86_64 version requirement is 1 which should support our older hardware).

@Dark98 Can you use Rufus to install Arch Linux to a USB? Or possibly burn it to a CD/DVD? Does that boot on your PC? I used Rufus to flash an internal SATA drive for testing and that did not work.

https://rufus.ie/en/
https://mirror.rackspace.com/archlinux/iso/2023.08.01/archlinux-2023.08.01-x86_64.iso

**Comment by pcking99** [comment]
Any updates on this? I get to the bootloader(GRUB) but after that i just get a blinking underscore. This is after a fresh install with everything installed. Tested with performance and minimal 3.3.0.

Laptop: Dell/Alienware M17X R3
GPU: Nvidia (dont remember which number but i guess 400 series)
Intel i7-2xxx

**Comment by LukeShortCloud** [comment]
Hey @pcking99 , thanks for reporting your issue. Since you are able to get to the GRUB boot menu, it sounds like you're issue is more likely to be related to this: https://github.com/LukeShortCloud/winesapOS/issues/638 . Although winesapOS does not officially support the older Fermi architecture you have, it should still work. I have an idea on how to workaround that that I'll post in the other GitHub Issue.

**Comment by LukeShortCloud** [comment]
My best guess for why legacy BIOS boot does not work (where a user cannot even get to the GRUB boot menu) on really old hardware is due to partition alignment. MBR is really strict about that whereas GPT is more relaxed. Even converting MBR to GPT and re-installing GRUB does not fix the issue leading me to believe this is an alignment issue (in that situation, only the boot sector at the beginning is modified, not all of the partition alignments).

This issue isn't just limited to winesapOS as I've also had problems booting modern Arch Linux and Debian images on my very old Windows XP computer. I spent a lot of my spare time trying to get this to work to no avail. For now, I added some documentation around this in our README.md.
