### ISSUE TITLE
Errors while booting the Performance image

### ISSUE THREAD

**Issue by ogstriker** [LukeShortCloud/winesapOS#752]
**Describe the bug or feature**
getting error while booting the ISO:

mount: /sys/firmware/efi/efivars: mount(2) system call failed: Operation not supported

failed to mount "UUID=" on real root

**Issue Type**
- [x ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. Boot ISO, select the Linux kernel and then I get the error 

**Expected behavior**
To boot and install normally

**Versions (please complete the following information):**
 - Version: [ex., 3.4.0]
 - Image type: [Performance]
 - Computer type: [PC]
 - Graphics vendor: [AMD]
 - Graphics card: [Ryzen 5 5500u Vega 7]

**Additional context**
I'm using an UEFI system and the ISO checksum matches.

**Comment by LukeShortCloud** [comment]
Hey @ogstriker thanks for reporting your issue!

You can safely ignore the first error. It is part of a workaround we have for systems with old and broken UEFI implementations. In our next release of winesapOS, we will autodetect if the workaround is needed or not and then adjust the boot settings accordingly.

The second error normally indicates that the Linux kernel does not have the correct drivers to fully read and use the drive that winesapOS is installed on. By default, we boot into the Linux LTS kernel which is a bit older. Could you try boot into Linux T2 instead? Specifically, the one with the "fallback initramfs" which has all of the kernel drivers available.

```
Arch Linux with Linux linux-t2 (fallback initramfs)
```

If that does not work, what drive (make/model/storage) are you using?

**Comment by ogstriker** [comment]
Hello, thanks for replying back.

Yes, I have tried booting with all kernels and no avail (including fallback initramfs). I'm using a NVME 256GB, but for the record Arch Linux and pretty much any other distro boots normally, the issue might be related to the workaround for old and broken UEFI systems.

**Comment by LukeShortCloud** [comment]
Interesting, thanks for confirming. Also good to know that other Linux distributions are working.

Is your 256 GB NVMe drive internal or external?

I would be very surprised if the UEFI workaround is causing your boot issues. I have around 10 PCs I test winesapOS with a variety of good, bad, and no UEFI support. That recent fix in winesapOS 3.4.0 from 3.3.0 has not changed anything related to boot compatibility on those test machines at least. You can remove the workaround with the following steps:

- On the GRUB boot menu, go down to `Arch Linux, with Linux linux-t2 (fallback initramfs)`.
- Press "e" to edit the boot option.
- Scroll down to the line that starts with `linux`.
- Remove `efi=noruntime` from that line.
- Press "CTRL" and "x" to boot with these new temporary settings.

Additionally, you can also try changing that line to where it is just `linux /vmlinuz=linux-t2 root=UUID=<UUID> rw` (keep your `<UUID>` there and delete everything after the `rw`). Since you are using a NVMe, it is possible that some of the IOMMU workarounds could be causing an issue.

Let me know if that helps or not.

**Comment by ogstriker** [comment]
Hello, thanks for helping.

My NVME is internal.

I tried removing the efi=noruntime but I got the same error.

Deleting everything after the `rw` parameter gave to me a different error output:

Waiting 10 seconds for device /dev/disk/by-uuid/myUUID ...
ERROR: device 'UUID=myUUID' not found. Skipping fsck.


I did a little bit of search and this UUID error looks like either systemd or init system problem.

**Comment by LukeShortCloud** [comment]
Thanks for testing those scenarios. The problem still seems to be fundamentally the same where the drive cannot be detected. These errors are actually before the init system takes over and are part of the early boot process.

Is that internal NVMe drive an Intel Optane drive? I have found lots of forums talking about those causing issues recently. Although I think it is unlikely to affect you since you are using a consumer grade AMD processor (that problem seems to only affect Intel CPU servers and workstations that use Intel Optane drives). One related fix you can try is to add `nvme_load=yes` to the boot argument (the line that starts with `linux`). https://github.com/LukeShortCloud/winesapOS/issues/753

**Comment by ogstriker** [comment]
Hi, my NVME is not an Intel Optane, it's just a regular one.

I tried using the `nvme_load=yes` argument but still no avail.

I want to increment that by removing the "quiet" argument on the booting process I get prompted with "starting systemd-udevd", then I get the "waiting 10 seconds for device /dev/disk/by_uuid/5b52bc9f-4842-4f58-bd4e-0630248d4e04 ... device not found. Skipping fsck" error. 

Sorry if I'm mistaken, but maybe the init system is taking part here, and some modules are not correctly loading, thus not detecting my drive UUID?

**Comment by LukeShortCloud** [comment]
You are right, something is going wrong when switching from the initramfs to systemd. I have most recently seen an issue on Fedora where a specific laptop had a driver that would rename the USB device after switching from the initramfs and booting into systemd. Very odd. The workaround was very device specific (it was an Arm laptop from Lenovo).

One thing I wonder about is if our final step of the build is causing any issues. We run `virt sys-prep` on the image to do a clean up of files and configuration settings. I made a special build for you that skipped that step.

Could you try this out and let me know if it works?

http://winesapos.lukeshort.cloud/repo/iso/winesapos-3.4.0/_test/winesapos-3.4.0-minimal-no-virt-sys-prep.img.zip
http://winesapos.lukeshort.cloud/repo/iso/winesapos-3.4.0/_test/winesapos-3.4.0-beta.1-minimal.sha512sum.txt

**Comment by LukeShortCloud** [comment]
Another thing I thought of: try setting `systemd.mask=winesapos-resize-root-file-system.service` as a Linux kernel boot argument (on that `linux` line). It has to be on the very first boot of a newly flashed image as that service only ever runs once and then disables itself. Perhaps it is some issue related to the root partition being expanded to use 100% of the available storage.

**Comment by ogstriker** [comment]
Hello! sorry for the delay in response, I was traveling.

Unfortunately neither using the custom ISO without 'virt sys-prep' worked, nor using the `systemd.mask=winesapos-resize-root-file-system.service` on the first boot of a newly flashed image, I'm still getting the same errors.

You mentioned you've seen a problem on fedora with a Lenovo ARM driver having problems that would rename the USB device while switching from initramfs to systemd, I also have a Lenovo IdeaPad 3 just in case there is some relation.

**Comment by LukeShortCloud** [comment]
Thanks for testing! Sorry to hear none of that helped. The Lenovo problem I mentioned is with Arm hardware (not x86) so it is not fully related. This is a really hard problem to troubleshoot and solve. We have encountered this generic error many times and fixed it for various different situations. I will give this more thought and research. Thanks again for helping test out solutions so far!

**Comment by LukeShortCloud** [comment]
Here are some more potential workarounds I found:

Boot with `module_blacklist=rtsx_pci,rtsx_pci_sdmmc` to disable conflicting PCIe drivers that have recently been known to cause boot issues with NVMe drives in the last few Linux kernel releases.

https://bbs.archlinux.org/viewtopic.php?id=288913

Boot with `nvme_core.default_ps_max_latency_us=0 pcie_aspm=off` to address power saving issues with NVMe drives.

https://bugs.archlinux.org/task/79439

In your BIOS, change the "SATA" setting to "AHCI" (yes, this is a workaround for NVMe). Then boot with `nvme_load=yes`

https://www.dell.com/support/kbdoc/en-us/000131901/loading-ubuntu-on-systems-using-pcie-m2-drives

In your BIOS, disable Secure Boot. The only major Linux distributions that support Secure Boot out-of-the-box are unmodified Fedora and Ubuntu distributions. It is very hard and extremely expensive for other distributions to support.

----

I double checked our `HOOKS` for `mkinitcpio` in winesapOS. They are loading up all of the necessary drivers for every type of drive (including NVMe). I even had a look at the [mkinitcpio source code](https://github.com/archlinux/mkinitcpio/tree/3bfe7dd33a45b66ba45a1231a0e22740dff7e7a8) to be sure.

**Comment by LukeShortCloud** [comment]
The first two issues from my last comment have been fixed as of Linux 6.6-rc4 and is not an issue in the `linux-t2` kernel shipped with winesapOS 3.4.0. https://github.com/torvalds/linux/commit/0e4cac557531a4c93de108d9ff11329fcad482ff

----

@ogstriker Disabling Secure Boot and setting the SATA mode to AHCI instead of RAID in your BIOS may help.

**Comment by LukeShortCloud** [comment]
@ogstriker winesapOS 4.0.0 is out with a lot of boot and driver improvements. I am hopeful that this will finally solve your issue. The performance and minimal images are available already. The secure image is still uploading.

- Change log: https://github.com/LukeShortCloud/winesapOS/blob/4.0.0/CHANGELOG.md
- Download: https://winesapos.lukeshort.cloud/repo/iso/winesapos-4.0.0/

We also have a new troubleshooting guide for boot issues related to all of this:

https://github.com/LukeShortCloud/winesapOS?tab=readme-ov-file#winesapos-not-booting

If you ever get a chance to try out winesapOS again, let me know if that works or not!
