### ISSUE TITLE
Can I get the source code for archiso

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#824]
Can I get the source code of WineSapOS But it's compatible with archiso because I'm more used to that

**Comment by LukeShortCloud** [comment]
Hey @GuestSneezeOSDev , thanks for reaching out! :-)

winesapOS takes a very different approach to being a live distribution. Instead of providing an ISO, we do a normal Arch Linux install process but tweak it so it is portable and bootable across a wide range of computers. `archiso` is not used.

Here are some hints that may help:
- Find all of the packages that winesapOS installs:
    - `grep -i -P "pacman_install|yay_install" scripts/winesapos-install.sh`
    - AUR packages come from a combination of the Chaotic AUR repository and our own winesapOS repository.
- winesapOS repository packages build process:
    - https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-alpha.0/scripts/repo/winesapos-build-repo.sh
- OS build options we support:
    - https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-alpha.0/CONTRIBUTING.md#environment-variables-for-installation
- How we handle some of our portability:
    - https://rootpages.lukeshort.cloud/latest/storage/bootloaders.html#usb-installation-with-both-legacy-bios-and-uefi-support

We used to have a more declarative approach similar to `packages.x86_64` from `archiso` back in the winesapOS 1.Y.Z days. I found it more useful for me and our community to make it read like an automated Arch Linux install guide. Most of our users have never used Linux before and this was this first exposure before they went off to do their own manual Arch Linux installation.

There is discussion about an [archupgrade](https://github.com/LukeShortCloud/winesapOS/issues/711) project that will provide (1) automated upgrades and (2) conversions to other Arch Linux distros such as ChimeraOS and winesapOS. The design for that will be declarative and might be how we do builds in the future, too. If you're interested in that, I can make sure you are included in those conversations.

Hopefully that helps! Let me know if you need anything else or if there is any specific way I can help out with GuestSneezeOS!

**Comment by GuestSneezeOSDev** [comment]
Thanks very much with the detailed reply, I just want to know how i can add custom repositories and packages to the iso

**Comment by LukeShortCloud** [comment]
You can customize those components here:
- Repositories: https://github.com/GuestSneezeOS-Official/GuestSneezeOS/blob/main/releng/pacman.conf
- Packages: https://github.com/GuestSneezeOS-Official/GuestSneezeOS/blob/main/releng/packages.x86_64

**Comment by LukeShortCloud** [comment]
The source code and documentation for the `archiso` project can be found here: https://gitlab.archlinux.org/archlinux/archiso/-/tree/master

**Comment by GuestSneezeOSDev** [comment]
Thanks for the support
