### ISSUE TITLE
Make it lighter

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#828]
**Describe the bug or feature**
A clear and concise description of what the bug or feature is.

**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

I want to install **WinesapOS** on my PC but WinesapOS requires 512+ GB and I have a 250 GB NVme drive and It keeps on freezing whenever I'm on the installing part

**specs**
- 250 GB NVme
- 8GB RAM
- intel core i5 8th gen
- x64
- UEFI
- 
**winesapos version**
4.0.0

**Comment by LukeShortCloud** [comment]
Hey @GuestSneezeOSDev , sorry to hear about your issues. I'd be happy to help out.

At most, the performance and secure images are 25 GiB in size. The minimal image is 8 GiB in size. winesapOS will automatically resize the root file system to fill up all addition space.

How exactly are you installing winesapOS?
1. Flashing to an external/portable NVMe drive in a USB enclosure.
2. Flashing to an internal NVMe drive.
3. Following the new [dual-boot guide](https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.0?tab=readme-ov-file#dual-boot).

Do you see any errors that you can share?

**Comment by GuestSneezeOSDev** [comment]
i just want to know can i make a 64 GB partition for winesapos?

**Comment by LukeShortCloud** [comment]
Okay, I see. You want to (1) install winesapOS on an internal drive and (2) use a smaller partition instead of using all of the available space.

You need winesapOS 4.1.0-beta.0 to do this: https://winesapos.lukeshort.cloud/repo/iso/winesapos-4.1.0/_test/

You need to create the partitions in this layout: https://github.com/LukeShortCloud/winesapOS/blob/main/CONTRIBUTING.md#partitions

Then follow the [dual-boot guide](https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.0?tab=readme-ov-file#dual-boot). The only difference is that you need create the EFI partition if it does not exist already (`mkfs.vfat /dev/<DEVICE><PARTITION_NUMBER>`).

**Comment by LukeShortCloud** [comment]
We will eventually provide an installer which will make this process a bit easier: https://github.com/LukeShortCloud/winesapOS/issues/370

**Comment by GuestSneezeOSDev** [comment]
thanks very much i appreciate it i might be able to help by making it all into a .sh file

**Comment by LukeShortCloud** [comment]
Thanks, simplifying these steps into a script would be great to help others!

**Comment by GuestSneezeOSDev** [comment]
the sh file can be found here https://github.com/GuestSneezeOSDev/WinesapDualboot
