### ISSUE TITLE
Tried to build winesapOS

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#859]
**Describe the bug or feature**
A clear and concise description of what the bug or feature is.

**Issue Type**
- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. `sudo journalctl -u reflector -f`
2. `git clone https://github.com/lukeshortcloud/winesapos.git`
3. `cd winesapos/scripts/`
4. `export WINESAPOS_DISTRO=arch`
5. `. ./env/winesapos-env-minimal.sh` (output `no such file or directory`)
6. `sudo bash ./winesapos-install.sh`
7. 

**Expected behavior**
I was expecting it to install and/or build winesapOS but it gave me an error  I will put a screenshot

**Screenshots**
<img width="473" alt="Screenshot 2024-07-21 213618" src="https://github.com/user-attachments/assets/bf9ee34c-a466-42d6-9f51-3687d9b96e32">

**System information (please complete the following information):**
- Version: [Not winesapOS (Arch Linux)]
- Image type: [None]
- Computer type: [PC]
- Graphics vendor: [Inte]
- Graphics card: [Intel Haswell]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**
* I Think it was one of these issues
   *  i was in `/dev/sda` instead of `/dev/sdb` (I was in C:/ instead of my flash drive) 
   * Installed Arch Linux incorrectly

**Comment by LukeShortCloud** [comment]
You don't need to run `reflector`, `winesapos-install.sh` does that automatically.

For the `no such file or directory` error, maybe there was a typo? The full path (including the git repository) is `winesapos/scripts/env/winesapos-env-minimal.sh`. You can find the exact location from your directory by running:

```
find . -name winesapos-env-minimal.sh
```

I'll have to add better/more documentation about changing the device as that is a common option to change. You're right, you need to configure the installer to use `sda` (or `sdb`) instead of the default of `vda`. You may also need to configure the installer to allow running on baremetal. Set these two environment variables before running the installer.

```
export WINESAPOS_DEVICE=sda
export WINESAPOS_BUILD_IN_VM_ONLY=false
```

When you run `sudo`, you need to use `sudo -E` instead for the environment variables to get passed through.

```
sudo -E bash ./winesapos-install.sh
```

Does that help? Let me know if you get further!

**Comment by GuestSneezeOSDev** [comment]
Thanks i will test it immediately, I was using this to build `GuestSneezeOS10_beta_prerelease` image, I was using the minimal image because GuestSneezeOS is meant to be a Lightweight Linux/Unix Based Distrobution

**Comment by GuestSneezeOSDev** [comment]
i will use the Live Image of Arch Linux
