### ISSUE TITLE
Install `emacs`

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#924]
**Describe the bug or feature**
I do not use `emacs` but some of my friends do and I would like to see it in winesapOS
**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
- Version: [4.1.0]
- Image type: [Minimal]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Intel Haswell ULT]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**

**Comment by LukeShortCloud** [comment]
I originally did not add it because, for some reason, it's over 300 MiB with all of its dependencies.

But we have the space so, sure, we might as well add it.

**Comment by GuestSneezeOSDev** [comment]
I have added this to my PR i will close this issue when it gets merged

**Comment by Calculator-a** [comment]
It would be easy if you type `pacman -S emacs`

**Comment by LukeShortCloud** [comment]
The goal here is to provide `emacs` out-of-the-box. It could be useful if there's an issue with winesapOS and users need to troubleshoot. It's a nice quality-of-life feature to have a text editor that you're comfortable with. Otherwise, it's one less thing `emacs` users have to install on their system.
